#!/bin/bash

#ubuntu下设置crontab的配置文件/etc/crontab
#通过修改conrtab文件前的#号来控制命令的开启与关闭

cronfile=/etc/crontab

job=$(sed -n "/$1/p" $cronfile)
if [  $# -eq 3 ] && [ -n "$job" ]   #判断输入的命令参数是否符合要求(要求命令存在于crontab表中)
then
    job_num=$(echo "$job" | grep '^#' &>/dev/null && echo 0 || echo 1)
    #返回0表示输入的查找命令jobname在crontab表中且处于关闭状态
    #返回为1则表示该命令jobname在crontab表中处于开启
    case $2 in
    --start)
        if [ $job_num -eq 0 ]  #判断在/etc/crontab表中的jobname前是否有#号
        then
            sed -i "/$1/s/^#//g" $cronfile
            echo "$1 is started!"
        else
            echo "$1 is already started!"
        fi;;
    --stop)
        if [ $job_num -eq 0 ]   #等于0，则命令处于关闭状态
        then
            echo "$1 job is already stopped!"
        else
            sed -i "/$1/s/^/#/" $cronfile
            echo "$1 job is stopped!"
        fi;;
    --list)                  #查看jobname命令目前处于什么状态
        if [ $job_num -eq 0 ]
        then
            echo "$1 job is stopped!"
        else
            echo "$1 job is started!"
        fi;;
    esac
else
    printf "input like this: ./cronb_ctrl jobname --list and more:
    options:
    --start:start your cron
    --stop:stop your cron
    --list:show the job status\n"
fi